apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: git-stats-exporter-role
  labels:
    {{- include "git-stats-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - src.bwag.me
  resources:
  - repos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - src.bwag.me
  resources:
  - repos/finalizers
  verbs:
  - update
- apiGroups:
  - src.bwag.me
  resources:
  - repos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch