# permissions for end users to view repoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-viewer-role
rules:
- apiGroups:
  - src.bwag.me
  resources:
  - repoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - src.bwag.me
  resources:
  - repoes/status
  verbs:
  - get
