---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - src.bwag.me
  resources:
  - repoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - src.bwag.me
  resources:
  - repoes/finalizers
  verbs:
  - update
- apiGroups:
  - src.bwag.me
  resources:
  - repoes/status
  verbs:
  - get
  - patch
  - update
