name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag git-stats-exporter:${GITHUB_REF#refs/*/}
        docker push ghcr.io/bwagner5/git-stats-exporter:${GITHUB_REF#refs/*/}
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm package --app-version ${GITHUB_REF#refs/*/} --version ${GITHUB_REF#refs/*/}  chart/git-stats-exporter/
        git checkout gh-pages
        helm repo index --merge index.yaml .
        git add git-stats-exporter-*
        git commit -m "publish git-stats-exporter ${GITHUB_REF#refs/*/}"
        git push -u origin gh-pages
        
